spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 1
        maxActive: 20
        maxOpenPreparedStatements: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 1
        name: a
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://132.246.27.12:8866/aep_subpush?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: aep_test
        password: test123
        validationQuery: select 'x'
    #kafka:
        bootstrap-servers: 180.107.140.215:9092,180.107.140.80:9092,180.107.140.161:9092
        producer:
            client-id: pandaer
    #quartz:
        job-store-type: jdbc
        properties:
            org:
                quartz:
                    jobStore:
                        class: org.quartz.impl.jdbcjobstore.JobStoreTX
                        clusterCheckinInterval: 10000
                        dataSource: a
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        isClustered: true
                        tablePrefix: QRTZ_
                        useProperties: false
                    scheduler:
                        instanceId: AUTO
                        instanceName: clusteredScheduler
                    threadPool:
                        class: org.quartz.simpl.SimpleThreadPool
                        threadCount: 10
                        threadPriority: 5
                        threadsInheritContextClassLoaderOfInitializingThread: true
    redis:
        host: 180.100.217.67
        port: 7000

